### ISSUE TITLE
Tissue not working

### ISSUE THREAD

**Issue by eproxus** [wolph/tissue#6]
Tissue doesn't seem to work for me. I expected it to run pep8 on any file that was imported by `nosetests` but it doesn't seem to do anything:

```
$ pep8 script.py
script.py:60:11: E221 multiple spaces before operator
$ nosetests --with-tissue script.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

If I put a test inside `script.py` it picks it up, so nose is definitely importing that module.

**Comment by wolph** [comment]
This may have been broken in the past but it works for me right now. If it's still broken please let me know how to reproduce :)
